// 한국 찬송가 목록 (주요 찬송가)
export const HYMNS = [
  { number: 1, title: "만복의 근원 하나님", category: "찬양과 경배", firstLine: "만복의 근원 하나님 찬송하옴이 합당하도다" },
  { number: 2, title: "큰 영화로신 주", category: "찬양과 경배", firstLine: "큰 영화로신 주 하나님 온 세상 다스리시네" },
  { number: 3, title: "성부 성자 성령", category: "찬양과 경배", firstLine: "성부 성자 성령 삼위일체 하나님" },
  { number: 21, title: "찬양하라 복되신 구세주 예수", category: "찬양과 경배", firstLine: "찬양하라 복되신 구세주 예수" },
  { number: 22, title: "기뻐하며 경배하세", category: "찬양과 경배", firstLine: "기뻐하며 경배하세 영광의 주님께" },
  { number: 28, title: "주 하나님 지으신 모든 세계", category: "찬양과 경배", firstLine: "주 하나님 지으신 모든 세계 내 마음속에 그리어볼 때" },
  { number: 40, title: "천지에 가득 차", category: "찬양과 경배", firstLine: "천지에 가득 차 주 영광 빛나니" },
  { number: 64, title: "예수 우리 왕이여", category: "예수 그리스도", firstLine: "예수 우리 왕이여 이 시간 우리와 함께하소서" },
  { number: 79, title: "저 높고 푸른 하늘과", category: "예수 그리스도", firstLine: "저 높고 푸른 하늘과 수많은 별들과" },
  { number: 89, title: "예수님은 누구신가", category: "예수 그리스도", firstLine: "예수님은 누구신가 우리 기쁨 되시며" },
  { number: 93, title: "구주 예수 그리스도", category: "예수 그리스도", firstLine: "구주 예수 그리스도 영원히 동일하니" },
  { number: 96, title: "할렐루야 우리 예수", category: "예수 그리스도", firstLine: "할렐루야 우리 예수 영광중에 오셨네" },
  { number: 100, title: "거룩 거룩 거룩 전능하신 주님", category: "성령", firstLine: "거룩 거룩 거룩 전능하신 주님" },
  { number: 170, title: "내 주를 가까이 하게 함은", category: "기도와 간구", firstLine: "내 주를 가까이 하게 함은 십자가 짐 같은 고생이나" },
  { number: 175, title: "기도하는 이 시간", category: "기도와 간구", firstLine: "기도하는 이 시간 달고 오묘한 그 시간" },
  { number: 200, title: "나 어느 곳에 있든지", category: "신뢰와 소망", firstLine: "나 어느 곳에 있든지 하늘 아버지 함께 하네" },
  { number: 210, title: "주 믿는 사람 일어나", category: "신뢰와 소망", firstLine: "주 믿는 사람 일어나 다 함께 힘을 합하세" },
  { number: 218, title: "예수 나를 위하여", category: "구원", firstLine: "예수 나를 위하여 십자가를 질 때에" },
  { number: 228, title: "세상 모든 풍파 너를 흔들어도", category: "신뢰와 소망", firstLine: "세상 모든 풍파 너를 흔들어도 내 영혼의 닻 내려라" },
  { number: 305, title: "나 같은 죄인 살리신", category: "구원", firstLine: "나 같은 죄인 살리신 주 은혜 놀라워" },
  { number: 340, title: "내가 예수 믿고서", category: "구원", firstLine: "내가 예수 믿고서 죄 사함 받으니" },
  { number: 348, title: "오 놀라운 구세주", category: "구원", firstLine: "오 놀라운 구세주 예수 내 주 밤낮으로 내 기쁨 되시는 주" },
  { number: 360, title: "나의 갈 길 다 가도록", category: "헌신", firstLine: "나의 갈 길 다 가도록 예수 인도하시니" },
  { number: 365, title: "주님의 뜻을 이루소서", category: "헌신", firstLine: "주님의 뜻을 이루소서 주님의 뜻을 이루소서" },
  { number: 400, title: "예수가 우리를 부르는 소리", category: "헌신", firstLine: "예수가 우리를 부르는 소리 저 부드러운 음성 들려라" },
  { number: 461, title: "내 주여 뜻대로", category: "헌신", firstLine: "내 주여 뜻대로 행하옵소서 이 몸과 맘을 다 드립나이다" },
  { number: 478, title: "주님과 같이", category: "교제와 협력", firstLine: "주님과 같이 나 걸어가면 이 세상 길이 넓어라" },
  { number: 484, title: "아 하나님의 은혜로", category: "감사", firstLine: "아 하나님의 은혜로 이 죄인이 왜 구원받았나" },
  { number: 497, title: "우리는 주님을 늘 배반하지만", category: "감사", firstLine: "우리는 주님을 늘 배반하지만 주님은 사랑하신다" },
  { number: 559, title: "어둔 밤 쉬 되리니", category: "천국과 소망", firstLine: "어둔 밝 쉬 되리니 잠자지 말고 깨어라" },
  { number: 570, title: "나의 영원하신 기업", category: "천국과 소망", firstLine: "나의 영원하신 기업 나의 기업 되시는 예수님" },
  { number: 589, title: "하나님의 나팔 소리", category: "천국과 소망", firstLine: "하나님의 나팔 소리 울려 퍼질 때에" },
];

export const HYMN_CATEGORIES = [
  "전체",
  "찬양과 경배",
  "예수 그리스도",
  "성령",
  "기도와 간구",
  "신뢰와 소망",
  "구원",
  "헌신",
  "교제와 협력",
  "감사",
  "천국과 소망",
];
